### ISSUE TITLE
Active VIP

### ISSUE THREAD

**Issue by 123thecong** [RuyeNet/NIIM-Unlocker#1]
Hello, I don't understand the last part when activating VIP,
Can you help me
UID: 36C7A74C49
DEVICE id: D110-E510040972
When I try to print, the machine says not receiving paper, if I turn off clash it prints normally but the text is blurry
![image](https://github.com/RuyeNet/NIIM-Unlocker/assets/140313811/14048eab-ed68-48eb-bde9-b1034400d48a)

**Comment by RuyeNet** [comment]
Congratulations, this shows that there is no problem with your operation, but I have not authorized you in the management background, please contact me at:
https://t.me/RuyeNetBot
